name: 'Bump Version'
on:
  push:
    branches:
      - 'foo'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-bump:
    name: 'Version Bump'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          ref: ${{ github.ref_name }}
      - name: 'Update Version'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
          git fetch origin ${GITHUB_REF_NAME}
          git checkout -B ${GITHUB_REF_NAME} origin/${GITHUB_REF_NAME}
          git pull
          if git show --exit-code ${GITHUB_SHA} -- package/version; then
            ./package/version.sh bump
          fi
          ./package/version.sh sub
          git add --update
          if git commit --message "Set Version: $(cat package/version)"; then
            git push origin ${GITHUB_REF_NAME}
          fi
